development:
  adapter: async

test:
  adapter: test

production:
  adapter: <%= ENV["REDIS_URL"].present? ? "redis" : "async" %>
  <% if ENV["REDIS_URL"].present? %>
  url: <%= ENV["REDIS_URL"] %>
  channel_prefix: finance_ai_assistant_production
  <% end %>
